# Expecting base image to be the Deep Learning Container image built by ../cu113/Dockerfile.e3.gpu
ARG BASE_IMAGE=""

FROM $BASE_IMAGE

# Add any script or repo as required
COPY train.py /var/train.py

ENTRYPOINT ["python", "/var/train.py"]
